#!/bin/bash

git config --global user.name "vinson_yuan"
git config --global user.email "yuandemo@outlook.com"
git config --global core.autocrlf input
git config --list
ssh-keygen -t rsa -C "yuandemo@outlook.com"
cat ~/.ssh/id_rsa.pub
